build: off

platform:
- x86
- x64

configuration:
- Debug
- Release

matrix:
  fast_finish: true

install:
- cinst ninja
- pip install bfg9000
- 9k build && cd build && ninja

test_script:
- ./termcolor.exe
